In [23]:
import pandas as pd
import glob, os

In [24]:
df = pd.read_csv("bro_bids_ses-1.csv", sep="\t", index_col=['Unnamed: 0'])

In [25]:
df.index.name = "ses-1"
df

         anat  fmap  func  runs_pe  runs_rest  runs_train
ses-1
sub-001     0     0     0        0          0           0
sub-002     0     0     0        0          0           0
sub-003     0     0     0        0          0           0
sub-004     0     0     0        0          0           0
sub-006     1     5     5        2          1           2
sub-007     1     5     5        2          1           2
sub-008     1     5     5        2          1           2
sub-009     1     6     6        2          1           3
sub-010     1     0     0        0          0           0
sub-011     1     5     5        2          1           2
sub-012     1     0     0        0          0           0
sub-013     0     0     0        0          0           0
sub-014     1     6     6        2          1           3
sub-015     1     5     5        2          1           2
sub-016     1     5     5        2          1           2
sub-017     0     0     0        0          0           0
sub-018     0     0     0        0          0           0
sub-019     1     5     5        2          1           2
sub-020     1     3     3        1          1           1
sub-021     1     5     5        2          1           2
sub-022     1     5     5        2          1           2
sub-023     1     5     5        2          1           2
sub-025     1     5     5        2          1           2
sub-026     1     5     5        2          1           2
sub-027     0     0     0        0          0           0
sub-028     1     5     5        2          1           2
sub-029     1     5     5        2          1           2
sub-030     1     5     5        2          1           2
sub-031     1     5     5        2          1           2
sub-032     1     5     5        2          1           2
sub-033     1     5     5        2          1           2
sub-034     1     5     5        2          1           2
sub-036     1     5     5        2          1           2
sub-037     1     0     0        0          0           0
sub-038     1     5     5        2          1           2
sub-039     1     5     5        2          1           2
sub-040     1     0     0        0          0           0
sub-041     1     5     5        2          1           2
sub-042     0     0     0        0          0           0
sub-043     1     5     5        2          1           2
sub-044     1     5     5        2          1           2
sub-045     0     5     5        2          1           2
sub-046     1     5     5        2          1           2
sub-047     1     6     6        2          1           3
sub-048     1     5     5        2          1           2
sub-049     1     5     5        2          1           2
sub-050     1     8     8        5          1           2
sub-051     1     7     7        4          1           2
sub-052     1     0     0        0          0           0
sub-053     1     5     5        2          1           2
sub-054     0     0     0        0          0           0
sub-055     1     5     5        2          1           2
sub-056     1     5     5        2          1           2